- Changed network policy API versions from networking.k8s.io/v1 to crd.projectcalico.org/v1 - Updated deny-all and research network policies to use Calico's selector and order fields - Enhanced post-install hook with improved connectivity testing including DNS lookup, port check, and IP ping validation - Removed TOA basic auth credentials from pre-install hook secret creation - Added comprehensive annotations to research network policy for better observability and compliance tracking

diff --git a/secure-enclave/templates/post-install-hook.yaml b/secure-enclave/templates/post-install-hook.yaml
--- a/secure-enclave/templates/post-install-hook.yaml
+++ b/secure-enclave/templates/post-install-hook.yaml
@@ -10,6 +10,8 @@ spec:
   template:
     metadata:
       name: "{{ include "secure-enclave.fullname" . }}-post-install-hook"
+      labels: 
+        role: {{ .Values.researchContainer.name }}
     spec:
       restartPolicy: Never
       containers:
@@ -20,8 +22,17 @@ spec:
         - -c
         args:
         - |
-          echo "Testing connectivity to google.com"
-          echo "Performing DNS lookup for google.com..."
-          nslookup google.com
-          echo "Testing ping to google.com..."
-          ping -c 3 google.com
+          echo "Testing connectivity to TOA"
+          nslookup {{ .Values.trustedOutputApp.name }}-svc.{{ .Release.Namespace }}.svc.cluster.local
+          nc -zv "{{ .Values.trustedOutputApp.name }}-svc" {{ .Values.trustedOutputApp.service.port }}
+          echo "Performing DNS lookup for {{ .Values.managementApp.endpoint }}..."
+          nslookup {{ include "secure-enclave.extractHostFromUrl" .Values.managementApp.endpoint }}
+          nslookup {{ include "secure-enclave.extractHostFromUrl" .Values.managementApp.endpoint }} | grep 'Address'| grep -oE '\b([0-9]{1,3}\.){3}[0-9]{1,3}\b' >> /tmp/ip_addresses
+          echo "Pinging all IPs from /tmp/ip_addresses:"
+          for ip in $(cat /tmp/ip_addresses); do
+            echo "Pinging IP: $ip"
+            if ! ping -c 2 $ip; then
+              echo "Ping failed for IP: $ip. Which means network restrictions are working as expected."
+              break
+            fi
+          done
